theme: jekyll-theme-cayman
lang: fr
title: Global Gam Jam ADICODE<sup>&reg;</sup> ISEN Lille
description: Vous trouverez ici toutes les informations utiles pour découvrir et vous inscrire à l’événement de la Global Game Jam® de l’ADICODE® ISEN Lille qui aura lieu du 26 au 28 janvier 2018, au 41 rue Vauban à Lille.
logo: ./favicon.ico
preregistration_link: https://goo.gl/forms/p1mPv4buarD7Df702